name: whatsapp_stickers
description: WhatsApp Stickers plugin for Flutter.
version: 0.1.0
homepage: https://github.com/Almas-Studio/whatsapp_stickers

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.applicazza.flutter.plugins.whatsapp_stickers
        pluginClass: WhatsappStickersPlugin
      ios:
        pluginClass: WhatsappStickersPlugin